- Makefile
- erlang.mk
- src/egithub.app.src
- src/egithub.erl
- src/egithub_req.erl
- src/egithub_req_in.erl
- src/egithub_req_out.erl
- src/egithub_sup.erl
- src/egithub_webhook.erl
- test/egithub.coverspec
Check [github docs](https://developer.github.com/v3#abuse-rate-limits) and handle such `403 Forbidden` responses when hitting its API
> Handle github rate limits

- CHANGELOG.md
- src/egithub.app.src
- src/egithub.erl
- src/egithub_req.erl
- src/egithub_req_out.erl
Add support for [Github Status API](https://developer.github.com/v3/repos/statuses/)
> Support for Github Status API

- Makefile
- erlang.mk
- src/egithub.erl
- src/egithub_json.erl
- src/egithub_req.erl
- src/egithub_sup.erl
- src/egithub_webhook.erl
- xref.config
So that, using the github status API, it can report statuses in github PRs.
> Add status support to egithub_webhook

- CHANGELOG.md
Updated change log to 0.1.13 version.
> [#42] Updated change log

- src/egithub_webhook.erl
Fix #46 and This issue it is linked to inaka/elvis#234
> [#46] Add erlang:get_stacktrace() to search errors in event() call

- CHANGELOG.md
- src/egithub.app.src
> [#48] Version bump 0.1.14

- src/egithub.app.src
> [#51] Removing jiffy from egithub.app.src

- src/CHANGELOG.md
- src/egithub.app.src
Fix #53 Version Bump to 0.1.15
> [#53] Version Bump to 0.1.15

- Makefile
- elvis.config
- rebar.config
Update elvis.config to add protocol_for_deps rules also.
> Use https protocol for git dependencies

- README.md
> [#4] Links to examples

- Makefile
- erlang.mk
- rel/test.config
- src/egithub_req.erl
- test/egithub_SUITE.erl
- test/egithub_json_SUITE.erl
> [#4] Tests

- rel/test.config
- test/egithub_SUITE.erl
> [#4] Remove test.config since it is not actually used

- .gitignore
- Makefile
- elvis.config
- erlang.mk
- rebar.config
- src/egithub.erl
- src/egithub_req.erl
- src/egithub_req_in.erl
- src/egithub_req_out.erl
- src/egithub_sup.erl
- src/egithub_webhook.erl
- test/egithub_SUITE.erl
- test/egithub_json_SUITE.erl
- test/egithub_json_example.erl
- test/egithub_meta_SUITE.erl
> Get the project up-to-date

- CHANGELOG.md
- src/egithub.app.src
> Version Bump to 0.1.18

- Makefile
- src/egithub_webhook.erl
> [Fix #75] Rename egithub_webhook:handle_pull_request/3

- rebar.config.script
Add rebar2 compatibility script as discussed in #82
> Fix build for rebar2

- src/egithub_webhook.erl
as the current spec (`{failed, integer()}`) is too specific and not required by any code handling the callbacks returned terms.
also make the target_url return value optional in the specs.
> fix egithub_webhook:handle_error spec

- CHANGELOG.md
- src/egithub.app.src
> [#136] Version Bump to 0.3.2

- README.md
- elvis.config
- src/egithub.erl
- src/egithub_webhook.erl
- test/egithub_SUITE.erl
More info about GitHub's [PR Reviews](https://developer.github.com/v3/pulls/reviews/)
> [Fix #138] Allow the users to user the new GitHub's PR review feature

- README.md
- src/egithub_webhook.erl
Also:
- Change API documentation URL to hexdocs
> [Fix #149] Fix dialyzer and code issues left after pull#146

- src/egithub_webhook.erl
[Fix #153] Make check pass when PR is approved
> [Fix #153] Make check pass when PR is approved

- src/egithub.erl
- test/egithub_SUITE.erl
Implement read part of Releases API support.
> Releases API

- CHANGELOG.md
- src/egithub.app.src
> [#159] Version Bump to 0.5.3

- CHANGELOG.md
- src/egithub.app.src
> Bump Version to 0.5.4

- src/egithub.erl
- src/egithub_req.erl
- src/egithub_webhook.erl
partially fix of this bug: https://github.com/inaka/elvis/issues/486
OTP 21 dialyzer gave a bunch of errors.
> fix dialyzer warnings for OTP 21

- src/egithub.erl
more `-spec()` fix based on OTP 21 dialyzer messages in `egithub_meta_SUITE:dialyzer/1`
https://github.com/inaka/erlang-github/issues/169
> OTP 21 dialyzer fixes in common tests

- src/egithub.erl
- test/egithub_SUITE.erl
Implementation of API to retrieve a single PR by its id.
> Implement API for retrieving a single pull request

- src/egithub.erl
- test/egithub_SUITE.erl
Adding API calls to get a single tag by its id, and a list of tags
including the ability to page through the tags using the "after"
query parameter.
> Implement API for retrieving tags

- src/egithub.erl
- test/egithub_SUITE.erl
I wrote the call paging call for the tag API modeled after the paging for the
github website not the github api. I've also changed the Tag variable to
TagSha to match the github api docs.
> Correct the tag API
